### ISSUE TITLE
Discovery strategy works fine when directly running the application but not working when running it as a docker container

### ISSUE THREAD

**Issue by manojooyala** [nikhilw/sarathi#1] opened 2017-04-13 04:49 UTC
Hi, 
   I am trying to use the declarative client in my nodejs application. The below configuration works fine when directly running the express application. But it throws the below connection refused error.
when i am running my nodejs application in a docker container. I have no clue regarding this. Any help will be really appreciated

`
const SarathiClientBuilder = require("sarathi");
`
`const clientBuilder = new SarathiClientBuilder();
`
`const ConsulDiscoveryStrategy = require("sarathi-consul-strategy").DiscoveryStrategy;
`
`const consulInstance = require('my-node-consul').getConsulInstance();
`
`const thesaurusClient = clientBuilder.setConfig({
`    
`restClient: { retry: 3 }, loadBalancer: { strategy: "round-robin" }
`
`}).setDiscoveryStrategy(new ConsulDiscoveryStrategy({ serviceId: "user-service", client: consulInstance }))
`
`.addMethod('getUser', '/api/getuser')
`
`.build();
`
`module.exports = thesaurusClient;
`

**This is the error message:** 

Giving up retries, declaring a failure. connect ECONNREFUSED 127.0.0.1:18137
{ Error: connect ECONNREFUSED 127.0.0.1:18137
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 18137 }

**Comment by nikhilw** [comment] 2017-04-13 11:06
Thank you for raising it. I will try to check what could be going wrong. Meanwhile, could you please tell me if 18137 is your application port on which 'user-service' is listening? Also, may I know what is the 'address' you are providing to consul when you are registering it?

**Comment by manojooyala** [comment] 2017-04-13 11:10
Yes. 'user-service' is running in port 18137. I am registering consul as
'consul' .

**Comment by nikhilw** [comment] 2017-04-13 12:20
Great! Lets say you registered the user-service with consul as:
`consul.agent.service.register({
    name: 'user-service',
    id: 'user-service-' + (Math.random()*1000),
    address: '<ipAddressOfService>'
    port: 18137
    }, function(err) {
        if (err) throw err;
});`

Could you please tell me what is the value of <ipAddressOfService> in your case, if you are providing an address? If not, you should provide here IP the of container in which your user-service is running, you can get this IP by running `docker inspect <containerId>`. If you have bound the container port on localhost by passing `-p` parameter, you should pass your docker-host IP as service address to consul.

**Comment by nikhilw** [comment] 2017-04-30 02:46
I'll be closing this as 'not a bug', if you feel otherwise, please feel free to reopen and update.

**Closed by nikhilw** 2017-04-30 02:46 UTC
Labels: invalid, question

**Comment by manojooyala** [comment] 2017-05-02 04:18
Just one quick suggestion here. In consul discovery strategy, the serviceDiscovery.nodes should have the array of service details which should contain the following,

                        _.forEach(result, (serviceDetails) => {
                            instance.serviceDiscovery.nodes.push({
                                address: serviceDetails.Node.Address,
                                port: serviceDetails.Service.Port,
                                url: `http://${serviceDetails.Node.Address}:${serviceDetails.Service.Port}/`
                            });
                        });

I am using  serviceDetails.Node.Address instead of  serviceDetails.Service.Address. Because when you are running your application in docker the serviceDetails.Node.Address will the containers ip instead of instance ip. I got it working when i used the above instance ip instead of containers ip.
